version: '3.4'

services:
  angulartourofheroes:
    image: angulartourofheroes
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
